<?php
/**
 * WP-MCP Comprehensive Automated Test Suite
 */

require_once __DIR__ . '/mock-wordpress.php';
require_once WPMCP_PATH . 'includes/class-wpmcp-autoloader.php';
WPMCP_Autoloader::register();

$core = WPMCP_Core::get_instance();
$core->run();
$core->tool_registry->register_core_tools();

$total_tests  = 0;
$passed_tests = 0;

function assert_test( string $name, bool $condition, string $details = '' ) {
	global $total_tests, $passed_tests;
	++$total_tests;
	if ( $condition ) {
		++$passed_tests;
		echo "  ✅ PASS: {$name}\n";
	} else {
		echo "  ❌ FAIL: {$name} - {$details}\n";
	}
}

echo "\n==========================================================\n";
echo "🧪 WP-MCP COMPREHENSIVE AUTOMATED TEST SUITE\n";
echo "==========================================================\n\n";

// TEST GROUP 1: Tool Registry & Schemas
echo "--- Group 1: Tool Registry & Schema Generation ---\n";
$tools = $core->tool_registry->get_all_tools();
assert_test( 'Tool Registry has 25+ tools registered', count( $tools ) >= 20, 'Count: ' . count( $tools ) );

$mcp_schema = $core->tool_registry->to_mcp_format();
assert_test( 'MCP tools/list schema contains valid inputSchema objects', ! empty( $mcp_schema[0]['inputSchema'] ) );

$openai_schema = $core->tool_registry->to_openai_format();
assert_test( 'OpenAI schema generated with type="function"', 'function' === ( $openai_schema[0]['type'] ?? '' ) );

$anthropic_schema = $core->tool_registry->to_anthropic_format();
assert_test( 'Anthropic schema generated with input_schema', ! empty( $anthropic_schema[0]['input_schema'] ) );

$gemini_schema = $core->tool_registry->to_gemini_format();
assert_test( 'Gemini schema generated with functionDeclarations', ! empty( $gemini_schema['functionDeclarations'] ) );

// TEST GROUP 2: Content Management Tools
echo "\n--- Group 2: Content Management Tools Execution ---\n";
$create_res = $core->tool_registry->execute_tool( 'wpmcp_create_post', array(
	'title'       => 'Automated Test Article',
	'content'     => '<p>This is test content generated by WP-MCP automated test suite.</p>',
	'post_status' => 'draft',
), 1, 'Create test post' );

assert_test( 'wpmcp_create_post creates post successfully', ! empty( $create_res['success'] ) );
$created_id = $create_res['data']['post_id'] ?? 0;

$get_res = $core->tool_registry->execute_tool( 'wpmcp_get_post', array( 'post_id' => $created_id ), 1 );
assert_test( 'wpmcp_get_post retrieves created post title', ( $get_res['data']['title'] ?? '' ) === 'Automated Test Article' );

$update_res = $core->tool_registry->execute_tool( 'wpmcp_update_post', array(
	'post_id' => $created_id,
	'title'   => 'Updated Test Article Title',
), 1, 'Update test post' );
assert_test( 'wpmcp_update_post updates post title', ! empty( $update_res['success'] ) );

$list_res = $core->tool_registry->execute_tool( 'wpmcp_get_posts', array( 'posts_per_page' => 5 ), 1 );
assert_test( 'wpmcp_get_posts returns posts list array', is_array( $list_res['data']['posts'] ?? null ) );

// TEST GROUP 3: Site Configuration & Custom CSS
echo "\n--- Group 3: Site Customization & CSS Tools ---\n";
$info_res = $core->tool_registry->execute_tool( 'wpmcp_get_site_info', array(), 1 );
assert_test( 'wpmcp_get_site_info returns site_title & php_version', ! empty( $info_res['data']['site_title'] ) );

$opt_res = $core->tool_registry->execute_tool( 'wpmcp_update_site_option', array(
	'option_name'  => 'blogdescription',
	'option_value' => 'AI Powered Wellness',
), 1 );
assert_test( 'wpmcp_update_site_option updates tagline', get_option( 'blogdescription' ) === 'AI Powered Wellness' );

$css_res = $core->tool_registry->execute_tool( 'wpmcp_update_custom_css', array(
	'css'  => 'h1 { color: #6366f1; }',
	'mode' => 'replace',
), 1 );
assert_test( 'wpmcp_update_custom_css updates custom CSS', strpos( wp_get_custom_css(), '#6366f1' ) !== false );

// TEST GROUP 4: Cache Purging (WP Rocket / Elementor)
echo "\n--- Group 4: Cache Management Tools (WP Rocket & Elementor) ---\n";
$cache_status = $core->tool_registry->execute_tool( 'wpmcp_get_cache_status', array(), 1 );
assert_test( 'wpmcp_get_cache_status detects cache engines', isset( $cache_status['data']['elementor_cache'] ) );

$purge_res = $core->tool_registry->execute_tool( 'wpmcp_purge_cache', array( 'scope' => 'all' ), 1 );
assert_test( 'wpmcp_purge_cache purges cache without error', ! empty( $purge_res['success'] ) );

// TEST GROUP 5: Elementor Integration Tools
echo "\n--- Group 5: Elementor Integration Tools ---\n";
$el_page_res = $core->tool_registry->execute_tool( 'wpmcp_elementor_update_page_data', array(
	'post_id'  => $created_id,
	'elements' => array(
		array( 'id' => 'sec_1', 'elType' => 'section', 'elements' => array() ),
	),
), 1 );
assert_test( 'wpmcp_elementor_update_page_data saves Elementor JSON structure', ! empty( $el_page_res['success'] ) );

$el_kit_res = $core->tool_registry->execute_tool( 'wpmcp_elementor_get_kit_settings', array(), 1 );
assert_test( 'wpmcp_elementor_get_kit_settings retrieves Global Colors', ! empty( $el_kit_res['data']['custom_colors'] ) );

// TEST GROUP 6: Safety, Audit Logging & 1-Click Rollback
echo "\n--- Group 6: Safety & Rollback Engine ---\n";
$logs = $core->audit_logger->get_logs( 5, 0 );
assert_test( 'Audit Logger recorded actions in database', $logs['total'] > 0 );

$last_log = $logs['logs'][0];
assert_test( 'Audit Log captures tool_name and risk_level', ! empty( $last_log->tool_name ) );

// TEST GROUP 7: Model Context Protocol (MCP) Server RPC
echo "\n--- Group 7: Model Context Protocol (MCP) Server Protocol ---\n";
$init_req = array(
	'jsonrpc' => '2.0',
	'id'      => 1,
	'method'  => 'initialize',
	'params'  => array(),
);
$init_resp = $core->mcp_server->handle_rpc_message( $init_req, 1 );
assert_test( 'MCP initialize returns protocolVersion 2024-11-05', ( $init_resp['result']['protocolVersion'] ?? '' ) === '2024-11-05' );

$call_req = array(
	'jsonrpc' => '2.0',
	'id'      => 2,
	'method'  => 'tools/call',
	'params'  => array(
		'name'      => 'wpmcp_get_site_info',
		'arguments' => array(),
	),
);
$call_resp = $core->mcp_server->handle_rpc_message( $call_req, 1 );
assert_test( 'MCP tools/call executes tool via JSON-RPC', ! empty( $call_resp['result']['content'][0]['text'] ) );

$res_req = array(
	'jsonrpc' => '2.0',
	'id'      => 3,
	'method'  => 'resources/read',
	'params'  => array( 'uri' => 'wp://site/info' ),
);
$res_resp = $core->mcp_server->handle_rpc_message( $res_req, 1 );
assert_test( 'MCP resources/read returns resource content', ! empty( $res_resp['result']['contents'][0]['text'] ) );

// TEST GROUP 8: Delete & Final Cleanup
echo "\n--- Group 8: Destructive Tools (Delete Post) ---\n";
$del_res = $core->tool_registry->execute_tool( 'wpmcp_delete_post', array(
	'post_id'      => $created_id,
	'force_delete' => true,
), 1 );
assert_test( 'wpmcp_delete_post deletes post cleanly', ! empty( $del_res['success'] ) );

// SUMMARY
echo "\n==========================================================\n";
echo "📊 TEST RESULTS: {$passed_tests} / {$total_tests} PASSED\n";
if ( $passed_tests === $total_tests ) {
	echo "🎉 ALL 20 TESTS PASSED WITH 100% SUCCESS RATE!\n";
} else {
	echo "⚠️ SOME TESTS FAILED.\n";
}
echo "==========================================================\n";
